name: echo

services:
  echo-app:
    image: echo-app:latest
    build: .
    container_name: echo-app
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////app/echo.db
    volumes:
      - /home/katrin/data/echo/echo.db:/app/echo.db
