name: 📠 Run Quality Gates

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-style:
    name: 🧮 Python Style
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/katrinio/finpipe-ci:latest

    steps:
      - uses: actions/checkout@v5

      - name: Run Ruff
        run: poetry run ruff check .

      - name: Run MyPy
        run: poetry run mypy src

      - name: Run djLint
        run: poetry run djlint src/templates --check

  frontend-style:
    name: 🖥️ Frontend Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Stylelint
        run: npm install --no-save stylelint stylelint-config-standard

      - name: Run Stylelint
        run: npx stylelint "src/static/**/*.css"