name: 📠 Run Quality Gates

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-style:
    name: 📟 Python Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: python -m pip install poetry==2.2.1

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run Ruff
        run: poetry run ruff check src

      - name: Run MyPy
        run: poetry run mypy src

      - name: Run djLint
        run: poetry run djlint src/templates --check

  frontend-style:
    name: 🖥️ Frontend Style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Install Stylelint
        run: npm install --no-save stylelint stylelint-config-standard

      - name: Run Stylelint
        run: npx stylelint "src/static/**/*.css"
